/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPhotoRouteImport } from './routes/p.$photo'
import { Route as AAlbumRouteImport } from './routes/a_.$album_'
import { Route as AAlbumPPhotoRouteImport } from './routes/a.$album_.p.$photo'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPhotoRoute = PPhotoRouteImport.update({
  id: '/p/$photo',
  path: '/p/$photo',
  getParentRoute: () => rootRouteImport,
} as any)
const AAlbumRoute = AAlbumRouteImport.update({
  id: '/a_/$album_',
  path: '/a/$album',
  getParentRoute: () => rootRouteImport,
} as any)
const AAlbumPPhotoRoute = AAlbumPPhotoRouteImport.update({
  id: '/a/$album_/p/$photo',
  path: '/a/$album/p/$photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$album': typeof AAlbumRoute
  '/p/$photo': typeof PPhotoRoute
  '/a/$album/p/$photo': typeof AAlbumPPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$album': typeof AAlbumRoute
  '/p/$photo': typeof PPhotoRoute
  '/a/$album/p/$photo': typeof AAlbumPPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a_/$album_': typeof AAlbumRoute
  '/p/$photo': typeof PPhotoRoute
  '/a/$album_/p/$photo': typeof AAlbumPPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/login'
    | '/settings'
    | '/a/$album'
    | '/p/$photo'
    | '/a/$album/p/$photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/login'
    | '/settings'
    | '/a/$album'
    | '/p/$photo'
    | '/a/$album/p/$photo'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/login'
    | '/settings'
    | '/a_/$album_'
    | '/p/$photo'
    | '/a/$album_/p/$photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRoute: typeof AlbumsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AAlbumRoute: typeof AAlbumRoute
  PPhotoRoute: typeof PPhotoRoute
  AAlbumPPhotoRoute: typeof AAlbumPPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$photo': {
      id: '/p/$photo'
      path: '/p/$photo'
      fullPath: '/p/$photo'
      preLoaderRoute: typeof PPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a_/$album_': {
      id: '/a_/$album_'
      path: '/a/$album'
      fullPath: '/a/$album'
      preLoaderRoute: typeof AAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$album_/p/$photo': {
      id: '/a/$album_/p/$photo'
      path: '/a/$album/p/$photo'
      fullPath: '/a/$album/p/$photo'
      preLoaderRoute: typeof AAlbumPPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AAlbumRoute: AAlbumRoute,
  PPhotoRoute: PPhotoRoute,
  AAlbumPPhotoRoute: AAlbumPPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
