/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPhotoRouteImport } from './routes/p/$photo'
import { Route as AAlbumRouteImport } from './routes/a/$album'
import { Route as AAlbumPhotoRouteImport } from './routes/a/$album/$photo'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPhotoRoute = PPhotoRouteImport.update({
  id: '/p/$photo',
  path: '/p/$photo',
  getParentRoute: () => rootRouteImport,
} as any)
const AAlbumRoute = AAlbumRouteImport.update({
  id: '/a/$album',
  path: '/a/$album',
  getParentRoute: () => rootRouteImport,
} as any)
const AAlbumPhotoRoute = AAlbumPhotoRouteImport.update({
  id: '/$photo',
  path: '/$photo',
  getParentRoute: () => AAlbumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$album': typeof AAlbumRouteWithChildren
  '/p/$photo': typeof PPhotoRoute
  '/a/$album/$photo': typeof AAlbumPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$album': typeof AAlbumRouteWithChildren
  '/p/$photo': typeof PPhotoRoute
  '/a/$album/$photo': typeof AAlbumPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$album': typeof AAlbumRouteWithChildren
  '/p/$photo': typeof PPhotoRoute
  '/a/$album/$photo': typeof AAlbumPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/a/$album'
    | '/p/$photo'
    | '/a/$album/$photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/a/$album'
    | '/p/$photo'
    | '/a/$album/$photo'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/a/$album'
    | '/p/$photo'
    | '/a/$album/$photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AAlbumRoute: typeof AAlbumRouteWithChildren
  PPhotoRoute: typeof PPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$photo': {
      id: '/p/$photo'
      path: '/p/$photo'
      fullPath: '/p/$photo'
      preLoaderRoute: typeof PPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$album': {
      id: '/a/$album'
      path: '/a/$album'
      fullPath: '/a/$album'
      preLoaderRoute: typeof AAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$album/$photo': {
      id: '/a/$album/$photo'
      path: '/$photo'
      fullPath: '/a/$album/$photo'
      preLoaderRoute: typeof AAlbumPhotoRouteImport
      parentRoute: typeof AAlbumRoute
    }
  }
}

interface AAlbumRouteChildren {
  AAlbumPhotoRoute: typeof AAlbumPhotoRoute
}

const AAlbumRouteChildren: AAlbumRouteChildren = {
  AAlbumPhotoRoute: AAlbumPhotoRoute,
}

const AAlbumRouteWithChildren =
  AAlbumRoute._addFileChildren(AAlbumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AAlbumRoute: AAlbumRouteWithChildren,
  PPhotoRoute: PPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
